package controller;

import Database.DatabaseAppointments;
import Database.DatabaseReports;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;
import model.Appointments;
import model.Contacts;
import util.ErrorHandling;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

/**Controller Class for Reports*/
public class Reports implements Initializable {
    public ComboBox reportCombo;
    public Button generateButton;
    public TextArea reportField;

    final String r1 = "Total Apts by Type and Month";
    final String r2 = "Contact Schedule";
    final String r3 = "Grand Total Hours";
    public TableView reportsTable;
    public TableColumn aptID;
    public TableColumn title;
    public TableColumn description;
    public TableColumn type;
    public TableColumn start;
    public TableColumn end;
    public ComboBox contactComboBox;
    public ComboBox selectMonth;
    public ComboBox typeCombo;
    public TableColumn cusID;
    public Button generateReport1;
    public Button generateReport2;
    public Button generateReport3;
    public TextField report3Field;
    public TextField report2Field;


    /**Returns User to CustomerController
     * @param actionEvent Action Event for Return Button*/
    public void onReturn(ActionEvent actionEvent) throws IOException {
        Parent root = FXMLLoader.load(getClass().getResource("/view/Customers.fxml"));
        Stage stage = (Stage) ((Node) actionEvent.getSource()).getScene().getWindow();
        Scene scene = new Scene(root, 1100, 550);
        stage.setTitle("Customers");
        stage.setScene(scene);
        stage.show();
    }

    /**Populates text field with reports by type and month generated by 2 database calls*/
    public void reportByTypeMonth(){
        String month = (String) selectMonth.getSelectionModel().getSelectedItem();
        String type1 = (String) typeCombo.getSelectionModel().getSelectedItem();
        ObservableList<Appointments> appointments =DatabaseReports.getReportByMonthType(month, type1);
        int appointmentsCount = appointments.size();

        report2Field.setText("Appointment count by type and month: "+appointmentsCount);
    }

    /**Populates table view with appointments with provided contact.*/
    public void reportByContactSchedule(){
        Contacts selectedContact = (Contacts) contactComboBox.getSelectionModel().getSelectedItem();
        int id = selectedContact.getContactID();
        ObservableList<Appointments> apts = DatabaseReports.getContactAppointments(id);

        if(apts.isEmpty()){
            reportsTable.setItems(apts);
            aptID.setCellValueFactory(new PropertyValueFactory<>("appointment_ID"));
            title.setCellValueFactory(new PropertyValueFactory<>("title"));
            description.setCellValueFactory(new PropertyValueFactory<>("description"));
            type.setCellValueFactory(new PropertyValueFactory<>("type"));
            start.setCellValueFactory(new PropertyValueFactory<>("startDateTime"));
            end.setCellValueFactory(new PropertyValueFactory<>("endDateTime"));
            cusID.setCellValueFactory(new PropertyValueFactory<>("customerId"));
            ErrorHandling.displayInformation("Chosen Contact has no upcoming appointments.");
        }

        else {
            reportsTable.setItems(apts);
            aptID.setCellValueFactory(new PropertyValueFactory<>("appointment_ID"));
            title.setCellValueFactory(new PropertyValueFactory<>("title"));
            description.setCellValueFactory(new PropertyValueFactory<>("description"));
            type.setCellValueFactory(new PropertyValueFactory<>("type"));
            start.setCellValueFactory(new PropertyValueFactory<>("startDateTime"));
            end.setCellValueFactory(new PropertyValueFactory<>("endDateTime"));
            cusID.setCellValueFactory(new PropertyValueFactory<>("customerId"));
        }
    }

    public void onSelectMonth(ActionEvent actionEvent) {
        typeCombo.setItems(null);
        String selectedMonth = (String) selectMonth.getSelectionModel().getSelectedItem();
        ObservableList<String> typeList = DatabaseReports.getReportByType(selectedMonth);
        typeCombo.setItems(typeList);
    }

    /**Generate button for report 1, calls reportByContactSchedule method
     * @param actionEvent On button press*/
    public void onGenReport1(ActionEvent actionEvent) {
        try {
            reportByContactSchedule();
        } catch (NullPointerException e) {
            ErrorHandling.displayError("Please select a contact from the combo box.");
        }
    }

    /**Generate button for report 2, calls reportByTypeMonth method
     * @param actionEvent On button press*/
    public void onGenReport2(ActionEvent actionEvent) {
        if(selectMonth.getSelectionModel().isEmpty() || typeCombo.getSelectionModel().isEmpty()){
            ErrorHandling.displayError("Please select a month and type from the combo boxes.");
        }
        else {
            reportByTypeMonth();
        }
    }

    /**Generate button for report 3, calls calls reportByTotalHours method
     * @param actionEvent On button press*/
    public void onGenReport3(ActionEvent actionEvent) {
        reportByTotalHours();
    }

    public interface CalculateTotalHours{
        int calculate(int hour1, int hour2);
    }

    /**LAMBDA 2 IS FOUND HERE AS WELL AS REPORT 3. Method populates text field with a grand total of hours needed
     * across all appointments. JUSTIFICATION: COULD BE USED TO PROVIDE ADDITIONAL FUNCTIONALITY TO THE APPLICATION
     * TO PROVIDE FAIR SCHEDULING FOR EACH CONTACT.*/
    public void reportByTotalHours(){
        ObservableList<Appointments> appointments = DatabaseAppointments.getAllAppointments();
        int totalHours = 0;

        for(Appointments a : appointments){
            CalculateTotalHours calculateTotalHours = (hour1, hour2) -> hour1 - hour2;
            totalHours += calculateTotalHours.calculate(a.getEndDateTime().getHour(), a.getStartDateTime().getHour());

        }
        report3Field.setText("Total hours for upcoming appointments: " +totalHours);
    }

    /**Initialize method populates combo box for contacts used in Report 1, as well as a combo box of applicable months
     * used in Report 2.*/
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        ObservableList<Contacts> contactList = DatabaseAppointments.getAllContacts();
        contactComboBox.setItems(contactList);
        ObservableList<String> monthList = DatabaseReports.getReportByMonth();
        selectMonth.setItems(monthList);
    }
}
